#!/usr/bin/env bash
# to install nginx server and configure to listen on port80
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
